name: enigma2 build new

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build enigma2
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/jbleyel/enigma2-buildenv/enigma2-buildenv:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Build enigma2
        env:
          CC: "gcc-14"
          CXX: "g++-14"
        run: |
          pip3 install six
          echo "compiling enigma2"
          autoreconf -i
          ./configure --with-libsdl=no --with-boxtype=nobox --enable-dependency-tracking ac_cv_prog_c_openmp=-fopenmp --with-gstversion=1.0 --with-textlcd
          make
          python -m compileall .
          echo done!
