name: updatepot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: updatepot
        run: |
          sudo apt-get -q update
          mkdir -p gettext
          cp po/gettext.tar ./gettext
          tar -xvf ./gettext/gettext.tar
          sudo cp ./gettext/inst/lib/* /usr/lib
          sudo cp ./gettext/inst/bin/* /usr/bin
          sudo rm -rf ./gettext
          git config --global user.email "bot@openatv.com"
          git config --global user.name "atv enigma po Bot"
          git config advice.addignoredfile false
          git clean -fd
          git checkout master
          cd po
          ./updatepot.sh
          cd ..
          git add -u
          git add * || :
          git commit -m "pot update"
          git remote add upstream https://${GITHUB_TOKEN}@github.com/jbleyel/enigma2.git > /dev/null 2>&1
          git push --quiet upstream master || echo "failed to push with error $?"
